### ISSUE TITLE
create new credential definition - page

### ISSUE THREAD

**Issue by veitmo** [amosproj/amos2022ss04-digital-identity#112]
## User story

1. As a {HR-Employee}
2. I want / need {to create a new credential which I can later assign to a DI}
3. So that {I can create a Mitarbeiterausweis for example}

## Acceptance criteria
* navigation bar has a tab for credentials
  * dropdown menu has button "create credentials"
* create credentials page includes:
  * fields:
    * name (string)
    * comment (optional, string)
  * tickbox;
    * "Revocable" (boolean) (needs to be adjusted in backend)
  * buttons:
    * "select icon" (link to a png can be inserted)
  * dropdown menu for schema selection:
    * nice addon-feature: have a search-field combined with the dropdown menu where user can search for schema
    * pick one schema from dropdown-menu
  * final button below all other things to create credential
  * feedback on success/error is displayed in frontend

## Definition of done (DoD)

- code peer-reviewed (by at least one team member)
- acceptance criteria met
- integrated into a clean build
- documentation updated
- code is well-formatted (according to our norms) and structure
- Code supports all functions/cases and all responses defined in the API
- no severe bugs during main functionalities (program should not stop executing due to these bugs, e.g. runtime exception in Docker)
- Bill of Materials updated if necessary
- 70% of the tests pass
- important functions shall be tested
- code has been deployed via Docker to the server

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by jackDS008** [comment]
Meine Tasks: revocable-Token im Backend durchreichen
