### ISSUE TITLE
add DI to existing credential via popup window

### ISSUE THREAD

**Issue by veitmo** [amosproj/amos2022ss04-digital-identity#114]
## User story

1. As a {HR-employee}
2. I want / need {to be able to add a DI to an existing credential}
3. So that {I can create e.g. a Mitarbeiterausweis for that DI}

## Acceptance criteria
  * pop-up window opens where HR-employee can select from the existing DIs
    * HR-employee needs to enter values for the attributes that the credential defines
    * send-button at bottom which triggers the assignment of a DI to a credential
  * After clicking send button, process runs through successfually and HR employee gets feedback on success/error in the frontend:
    * DI is really linked to credential
    * Credential information can be seen in Lissi Wallet
   
## Note from SD meeting:
   * connections/all has to be adjusted: merge local database (name, surname, email) with lissi/api/connections/all
   * note: please implement a new controller in the backend called "CredentialController", which differs from the current "CredentialDefinitionController"

## Definition of done (DoD)

- code peer-reviewed (by at least one team member)
- acceptance criteria met
- integrated into a clean build
- documentation updated
- code is well-formatted (according to our norms) and structure
- Code supports all functions/cases and all responses defined in the API
- no severe bugs during main functionalities (program should not stop executing due to these bugs, e.g. runtime exception in Docker)
- Bill of Materials updated if necessary
- 70% of the tests pass
- important functions shall be tested
- code has been deployed via Docker to the server

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by jackDS008** [comment]
@steve-237 Ich fange mal mit dem Backend an. Du kannst dann mit dem Frontend beginnen.

**Comment by jackDS008** [comment]
Tests im backend: PR erstellt

**Comment by jackDS008** [comment]
Backend tests in pull requests #226

**Comment by jackDS008** [comment]
@steve-237 Wie weit bist du mit den Tests im Frontend?

**Comment by steve-237** [comment]
Ich bin damit surch

**Comment by annikakrause** [comment]
> Ich bin damit durch

Kannst du dann dazu einen PR erstellen?

**Comment by steve-237** [comment]
> > Ich bin damit durch
> 
> Kannst du dann dazu einen PR erstellen?

ich hatte schon seit ein paar Tagen das auch gemacht und es wurde auch gereviewt
