### ISSUE TITLE
Create new DI: new DI is created even if email couldn't be sent

### ISSUE THREAD

**Issue by annikakrause** [amosproj/amos2022ss04-digital-identity#117]
**Describe the bug**
When you create a new DI, a email gets sent to the new user. If the email couldn't be sent, a error message pops up.
BUT even if the sending of the email was not successfull, the new DI gets created and added to the database.

**To Reproduce**

1. Do not set up your email relay (do not enter your email and password in application.properties)
2. Go to 'Create new Digital Identity'
3. Enter required information
4. Click on 'Register'
5. A error message pops up, that the email couldn't be sent, so the creation of a new DI wasn't successful
6. Look into your database or go to 'Overview of Digital Identities', the DI you just tried to create is added to the database

**Expected behavior**
If it was not possible to send an email with the QR code, the new DI shouln't get created.

**Comment by valentinBraeutigam** [comment]
I think it's fixed by backend refactoring #134, right? @Idontker @Jean28518

**Comment by Jean28518** [comment]
No it's not, because we need an invitation link for sending the mail. 

For an invitation link we need to create a connection (DI)

**Comment by valentinBraeutigam** [comment]
Okay but it's not saved in our database. So we would have to delete the Connection in Lissi and maybe write a delete function in our backend which we will need somewhen anyway?

**Comment by Idontker** [comment]
if we finish the implementation of remove (so that it disables the connection at lissi), the bug would be fixed.
Currently our remove looks like this: 
```java

public class DIConnectionService {
   /* ... */
    public ResponseEntity<String> remove(Integer id) {
        Optional<User> user = userRepository.findById(id);
        if (user.isPresent()) {
            return remove(user.get());
        } else {
            return ResponseEntity.status(400).body("User with id " + id + " not found.");
        }
    }

    public ResponseEntity<String> remove(User user) {
        return remove(user, true, true);
    }

    public ResponseEntity<String> remove(User user, boolean removeCreds, boolean removeProofs) {
        userRepository.delete(user);
        // TODO:
        // lissiApiService.removeConnection(user.getConnectionId(), removeCreds,
        // removeProofs);
        return ResponseEntity.status(200).body("Successfully removed connection.");
    }
   /* ... */
}
```
