### ISSUE TITLE
Feld 'connectionId' in Datenbank anlegen

### ISSUE THREAD

**Issue by jackDS008** [amosproj/amos2022ss04-digital-identity#157]
**Describe the bug**
Beim Anlegen einer neuen Connection soll die connectionId (String) in der Datenbank gespeichert werden. Momentan wird nur die invitationUrl gespeichert, was ein späteres zuordnen von connections aus Lissi zu User aus der Datenbank unmöglich macht.

Die Methode getAllConnections() im DIConnectionService soll nun die Connections aus Lissi mit denen aus der Datenbank mergen können. Hierfür kann der auskommentierte Code benutzt werden.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Idontker** [comment]
@jackDS008 
Bist du dir sicher, dass der Fehler noch aktuell ist? Ich dachte, dass ich das vor ein paar Tagen eingebaut habe.

**Comment by jackDS008** [comment]
@Idontker Also im Main-Branch ist zumindest noch nichts. Die id des Entity/Model User (also aus der Datenbank) ist ein Integer mit automatisch generierten Wert beim Anlegen.

```java
@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;
```

Hier müsste der Type allerdings String sein, um die id von Connections von Lissi wie "92707924-644b-43d3-8a10-7aa779ffc8e9" zu speichern. Dies muss dann auch noch in der Datenbank angepasst werden.

**Comment by jackDS008** [comment]
Ich bin mir nur nicht sicher, ob das wirklich ein Bug ist oder eher ein offenes Issue. Da können wir im Planning mal drüber reden und dann entscheiden
