### ISSUE TITLE
Overview of DI values for open credentials, open proofs, connection status

### ISSUE THREAD

**Issue by TamaraHoock** [amosproj/amos2022ss04-digital-identity#171]
## User story

1. As a {HR-employee}
2. I want / need {to be able to see all connected values for open credentials, open proofs, connection status }
3. So that {}

## Acceptance criteria

* backend:
 * connect related data about open credential, open proofs, connection status to the DI
 * establish automated updates on status of open credential, open proofs, connection for each DI
* frontend:
 * display current information/status of open credential, open proofs, connection of the related DI in column on Overview DI 
 * this should replace the existing dummy data/empty fields

## Definition of done (DoD)

- code peer-reviewed (by at least one team member)
- acceptance criteria met
- integrated into a clean build
- documentation updated
- code is well-formatted (according to our norms) and structure
- Code supports all functions/cases and all responses defined in the API
- no severe bugs during main functionalities (program should not stop executing due to these bugs, e.g. runtime exception in Docker)
- Bill of Materials updated if necessary
- 70% of the tests pass
- important functions shall be tested
- code has been deployed via Docker to the server

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by jackDS008** [comment]
Alternative: columns "open credential" and "open proofs" should be removed
