### ISSUE TITLE
Log-out Button

### ISSUE THREAD

**Issue by TamaraHoock** [amosproj/amos2022ss04-digital-identity#195]
## User story

1. As a {HR-employee}
2. I want / need {a button to leave DIdentity}
3. So that {log-out from DIdentity}

## Acceptance criteria

- Create log-out button with an Icon (closing door icon)
- Embed the button right corner in line with menu 
- Check mock-up design for inspiration

## Definition of done (DoD)

- code peer-reviewed (by at least one team member)
- acceptance criteria met
- integrated into a clean build
- documentation updated
- code is well-formatted (according to our norms) and structure
- Code supports all functions/cases and all responses defined in the API
- no severe bugs during main functionalities (program should not stop executing due to these bugs, e.g. runtime exception in Docker)
- Bill of Materials updated if necessary
- 70% of the tests pass
- important functions shall be tested
- code has been deployed via Docker to the server

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by Jean28518** [comment]
Done with #246
