### ISSUE TITLE
Adjustable size of columns in tables (e.g. overview pages)

### ISSUE THREAD

**Issue by TamaraHoock** [amosproj/amos2022ss04-digital-identity#208]
## User story

1. As a {HR-employee
2. I want / need to be able to adjust the width of each column
3. So that {I can see the full length of information about the DI

## Acceptance criteria

- Create responsive table, so that all (DI) information is fully displayed in each row and column 
- put a maximum width for each column, so that big email adresses don't crash the whole table
- if an email adress is larger than the maximum width, show it by hovering over the email adress
- optionally: Moving the cursor to the head column should allow the user to adjust the width of each column manually

## Definition of done (DoD)

- code peer-reviewed (by at least one team member)
- acceptance criteria met
- integrated into a clean build
- documentation updated
- code is well-formatted (according to our norms) and structure
- Code supports all functions/cases and all responses defined in the API
- no severe bugs during main functionalities (program should not stop executing due to these bugs, e.g. runtime exception in Docker)
- Bill of Materials updated if necessary
- 70% of the tests pass
- important functions shall be tested

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by Idontker** [comment]
https://medium.com/@imdebasispanda/resize-table-column-angular-5cb58b67367
