### ISSUE TITLE
Detailed overview of one proof

### ISSUE THREAD

**Issue by TamaraHoock** [amosproj/amos2022ss04-digital-identity#240]
## User story

1. As a HR-employee
2. I want / need a to get a detailed view of a proof template
3. So that I can see the important content of a proof templates and see the proof's corresponding credential definitions

## Acceptance criteria

* If you click on a proof template, more details about this proof template are displayed (as done for the schemas #95  & credentials #136)
* table displayed
* HR-employee sees overview of attributes
* HR-employee sees overview of self-attested attributes
* HR-employee sees time of creation of proof [and version?]
* HR-employee sees overview over credential definitions using this proof template
* HR-employee can search for DIs/connection using this proof template
  *  if possible: all actions of the proofs with respect to DIs are displayed   
      * when was the proof request send to a DI
      * when was the proof verified for a DI

## Definition of done (DoD)

- code peer-reviewed (by at least one team member)
- acceptance criteria met
- integrated into a clean build
- documentation updated
- code is well-formatted (according to our norms) and structure
- Code supports all functions/cases and all responses defined in the API
- no severe bugs during main functionalities (program should not stop executing due to these bugs, e.g. runtime exception in Docker)
- Bill of Materials updated if necessary
- 70% of the tests pass
- important functions shall be tested
- Code has been deployed via Docker to the server

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by Jean28518** [comment]
> HR-employee can search for DIs/connection using this proof template
> 
>     if possible: all actions of the proofs with respect to DIs are displayed
>         when was the proof request send to a DI
>         when was the proof verified for a DI

This one is currently not fulfilled
