### ISSUE TITLE
Automatically Issue Credential With Data Provided By Proof

### ISSUE THREAD

**Issue by Idontker** [amosproj/amos2022ss04-digital-identity#243]
## User story

1. As a HR-employee
2. I want / need that after the owner of a connection has answered to a proof request (thus sent self-attested attributes via Lissi Wallet) a final credential which possesses all attributes is created for that connection
3. So that the connection has a final credential which resembles the full Mitarbeiterausweis for example.

## Acceptance criteria

* process should be:
  * HR-employee creates "basic" credential definition which is used for the proof template
  * HR-employee creates "final" credential definition which includes the attributes from the basic credential definition plus the self-attested attributes
    * With the help of this "final" credential definition, a credential which holds all information will be issued
  * HR-employee creates the proof template and defines all self-attested attributes

  * Proposal: In the process of the proof template creation, provide the HR employee with a list where he can select the final credential definition (must already exist in Lissi at that moment) which should be used for the final credential creation

* Expected Functionality for now:
  *  after a proof request is answered from holder of the DI/connection via the Lissi Wallet, a credential based on the final credential definition (which has been linked to the basic credential definition or the proof template before) is created and visible in Lissi wallet.
  * attributes from proof template and basic credential definition are matched with attributes of the final credential definition based on their name. Thus, attribute names must match (suggestion from POs)
  * currently, the process is triggered via automatic checks on a fixed timely basis (e.g. every 30 mins): if new proof requests have been answered, trigger process

![grafik](https://user-images.githubusercontent.com/92971164/177590864-0ae89e03-1b49-4c6a-b852-e5b847a4caf9.png)

## Definition of done (DoD)

- code peer-reviewed (by at least one team member)
- acceptance criteria met
- integrated into a clean build
- documentation updated
- code is well-formatted (according to our norms) and structure
- Code supports all functions/cases and all responses defined in the API
- no severe bugs during main functionalities (program should not stop executing due to these bugs, e.g. runtime exception in Docker)
- Bill of Materials updated if necessary
- 70% of the tests pass
- important functions shall be tested
- Code has been deployed via Docker to the server

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by Idontker** [comment]
@TamaraHoock @veitmo From a technical point of view, I would require the final credential when creating a proof template. This way, the linking makes more sense (as you define the self attested attributes within the proof template)

**Comment by veitmo** [comment]
@Idontker @TamaraHoock you are right. I flipped the two steps in the process description. I hope that it makes more sense now
