### ISSUE TITLE
Change password/login/forgot password page according to Mockup

### ISSUE THREAD

**Issue by TamaraHoock** [amosproj/amos2022ss04-digital-identity#266]
## User story

1. As a HR-employee
2. I want / need the UI design to be appealing and according to the adorsys styelguide
3. So that I enjoy working with DIdentiy 

## Acceptance criteria

- Update frontend design based on mock-up design on Figma, which is based on adorsys style guide
- Use as Figma example pages: "Settings Change Password", "Forgotten Password", "Initial Password Change"

- Should be applied to all "<3 Password" pages
  - Change Password
  - Forgotten Password
  - Initial Password Change

- minor deviations for creative freedom are allowed

## Definition of done (DoD)

- code peer-reviewed (by at least one team member)
- acceptance criteria met
- integrated into a clean build
- documentation updated
- code is well-formatted (according to our norms) and structure
- Code supports all functions/cases and all responses defined in the API
- no severe bugs during main functionalities (program should not stop executing due to these bugs, e.g. runtime exception in Docker)
- Bill of Materials updated if necessary
- 70% of the tests pass
- important functions shall be tested
- Code has been deployed via Docker to the server

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by veitmo** [comment]
@annikakrause Hi, ist das Issue noch korrekterweise im Product Backlog? Will nur sichergehen, damit  wir nachher im Team Meeting Bescheid wissen, ob das nochmal für nächsten Sprint eingeplant werden soll

**Comment by annikakrause** [comment]
Ja @veitmo, das habe ich diesen sprint nicht mehr dazugenommen, kann ich aber nächsten sprint gerne machen :)
