### ISSUE TITLE
Pop-up windows according to Mockup

### ISSUE THREAD

**Issue by TamaraHoock** [amosproj/amos2022ss04-digital-identity#267]
## User story

1. As a HR-employee
2. I want / need an appealing UI design wccording to the adorsys styelguide
4. So that I enjoy working with DIdentiy 

## Acceptance criteria

- Update frontend design based on mock-up design on Figma, which is based on adorsys style guide
- Use as example pages "Digital Identity - Create Pop-up window"

- Should be applied to all "Pop-up" windows for
  - Digital Identity
  - Schemas
  - Credential Definitions
  - Proofs
- minor deviations for creative freedom are allowed

## Definition of done (DoD)

- code peer-reviewed (by at least one team member)
- acceptance criteria met
- integrated into a clean build
- documentation updated
- code is well-formatted (according to our norms) and structure
- Code supports all functions/cases and all responses defined in the API
- no severe bugs during main functionalities (program should not stop executing due to these bugs, e.g. runtime exception in Docker)
- Bill of Materials updated if necessary
- 70% of the tests pass
- important functions shall be tested
- Code has been deployed via Docker to the server

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by Jean28518** [comment]
The size of the windows should also be bigger :)

**Comment by Idontker** [comment]
![image](https://user-images.githubusercontent.com/53585343/180600309-aa1df373-2dbf-4703-bcaa-f1d94dfb4396.png)
please fix

**Comment by Idontker** [comment]
![image](https://user-images.githubusercontent.com/53585343/180622268-395be9f4-dfed-4766-a223-1db9a604654f.png)
![image](https://user-images.githubusercontent.com/53585343/180622276-64e52d33-ca2e-4c16-8418-ef0b7386c335.png)

more bugs more bugs more bugs
