### ISSUE TITLE
Finalize user, (technical) design, and build/deploy documentation

### ISSUE THREAD

**Issue by veitmo** [amosproj/amos2022ss04-digital-identity#295]
## User story

1. As a {}
2. I want / need {}
3. So that {}

## Acceptance criteria
- (technical) design = Software architecture (Jannik)
- user documentation with all functions (Steve)
- build/deploy documentation (Jean)

## Definition of done (DoD)

- code peer-reviewed (by at least one team member)
- acceptance criteria met
- integrated into a clean build
- documentation updated
- code is well-formatted (according to our norms) and structure
- Code supports all functions/cases and all responses defined in the API
- no severe bugs during main functionalities (program should not stop executing due to these bugs, e.g. runtime exception in Docker)
- Bill of Materials updated if necessary
- 70% of the tests pass
- important functions shall be tested
- Code has been deployed via Docker to the server

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by jackDS008** [comment]
In unserem [Excel Dokument](https://docs.google.com/spreadsheets/d/15sRcllInzAicmv35otwEbMGrM8mnC5RqOYRXJjoAbLo/edit#gid=1757988404
) brauchen wir Links zu den einzelnen Dokumentationen.

**Comment by jackDS008** [comment]
@steve-237 and I are finished.

@Jean28518 How about you? A link to your documentation is missing in the  [Excel Dokument](https://docs.google.com/spreadsheets/d/15sRcllInzAicmv35otwEbMGrM8mnC5RqOYRXJjoAbLo/edit#gid=1757988404
) . Just move it to Awaiting review when you've finished

**Comment by Jean28518** [comment]
I am done with the document but need to adjust some things on our main branch.
