### ISSUE TITLE
Bug in navigation bar

### ISSUE THREAD

**Issue by annikakrause** [amosproj/amos2022ss04-digital-identity#97]
**Describe the bug**
There is a developer error when clicking the menu possibilities at the navigation bar:
ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked.

**To Reproduce**

1. Go to '[...](http://localhost:4200/)'
2. Click on the navigation menu
4. See error in console

**Expected behavior**
No error

**Comment by Idontker** [comment]
Done in sprint 5 https://github.com/amosproj/amos2022ss04-digital-identity/commit/8b9cdf974b0592bb76a4d87a3d35fe9834c38272
