### ISSUE TITLE
Navigation bar: wrong menu point highlighting

### ISSUE THREAD

**Issue by annikakrause** [amosproj/amos2022ss04-digital-identity#98]
**Describe the bug**
The current menu point should be highlighted, but that is not always true:
a) after refreshing the page, sometimes no menu point is highlighted, sometimes the "Home" menu point is highlighted, even if you are not on the home-page
b) if you click on another menu point than "Home" without selecting a subcategory (which would lead to another page), the menu point you clicked on stays highlighted even if you don't change the page

Additionally, in the subcategories of "Schema" and "Digital Identity", always the first subcategory is highlighted.

**To Reproduce**

a)
1. Go to another page than that is available by the navigation menu
2. Refresh the page
3. See that no menu point is highlighted OR (if you refresh the "Overview of digital identities"-page) the "Home" menu point is higlighted

b)
1. Go to home or any other page that is available by the navigation menu
2. Click on "Digital Identity" or "Schema"
4. Do not select one of the two options, click somewhere else on the page so that the subcategory menu disappears
5. See that the clicked menu point, not the current one, is highlighted

**Expected behavior**
The current menu point should be highlighted.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox

**Comment by Idontker** [comment]
Done in sprint 5 https://github.com/amosproj/amos2022ss04-digital-identity/commit/8b9cdf974b0592bb76a4d87a3d35fe9834c38272
